version: "3"

services:
    ubuntu:
        build:
            context: ubuntu
            args:
                - UBUNTU_VERSION=16.04
        image: docker_gnucash
        container_name: docker_gnucash1
        ports:
            - "5901:5901"
            - "6901:6901"
